In [13]:
import numpy as np
x=np.array([35,6,57,9.8])
print(x)
print(type(x))
print(x.dtype)

[35.   6.  57.   9.8]
<class 'numpy.ndarray'>
float64


In [17]:
a2=np.array([[23,45],[37,57]])
print(a2)
print(type(a2))

[[23 45]
 [37 57]]
<class 'numpy.ndarray'>


In [21]:
a =np.array([10,20,30,40])
b=a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [25]:
a =np.array([10,20,30,40,50,60])
b=a.reshape(3,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]
 [50 60]]
(3, 2)


In [29]:
c=np.arange(3,20)
print(c)
type(c)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


numpy.ndarray

In [33]:
c=np.arange(1,9)
print(c)
type(c)

[1 2 3 4 5 6 7 8]


numpy.ndarray

In [35]:
d=np.array([1.3467,3.10987,4.91236])
np.around(d,2)

array([1.35, 3.11, 4.91])

In [37]:
print(np.sqrt(d))

[1.16047404 1.76348235 2.21638444]


In [39]:
print(np.around(np.sqrt(d),2))

[1.16 1.76 2.22]


In [47]:
a1=np.array([[3,4,5,8],[7,2,8,np.NAN]])
print(a1)
a1.dtype

[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]


dtype('float64')

In [51]:
a1_copy1=a1.astype(float)
a1_copy1.dtype
            

dtype('float64')

In [53]:
a1_copy1=a1.astype(str)
print(a1_copy1)
a1_copy1.dtype
            

[['3.0' '4.0' '5.0' '8.0']
 ['7.0' '2.0' '8.0' 'nan']]


dtype('<U32')

In [55]:
a1_copy1=a1.astype(complex)
print(a1_copy1)
a1_copy1.dtype
            

[[ 3.+0.j  4.+0.j  5.+0.j  8.+0.j]
 [ 7.+0.j  2.+0.j  8.+0.j nan+0.j]]


dtype('complex128')

In [59]:
#mathematical operations 
a2=np.array([[3,4,5],[6,7,8],[8,9,2]])
a2

array([[3, 4, 5],
       [6, 7, 8],
       [8, 9, 2]])

In [61]:
print(a2.sum(axis=1))
print(a2.sum(axis=0))

[12 21 19]
[17 20 15]


In [73]:
print(np.mean(a2, axis=1))
print(np.mean(a2, axis=0))

[4.         7.         6.33333333]
[5.66666667 6.66666667 5.        ]


In [77]:
#matrix operation 
a3=np.array([[3,4,5],[7,8,9],[2,6,9]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[3 4 5]
 [7 8 9]
 [2 6 9]]
[[0 4 5]
 [7 0 9]
 [2 6 0]]


In [85]:
a=np.array([[1,2],[3,4]])#multiplication matrix
b=np.array([[5,6],[7,8]])
c=np.matmul(a,b)
print(c)

[[19 22]
 [43 50]]


In [87]:
#print transpose
print(a.T)
print(b.T)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [103]:
a4=np.array([[3,4,5],[7,2,8],[9,1,6],[10,9,18]])
a4

array([[ 3,  4,  5],
       [ 7,  2,  8],
       [ 9,  1,  6],
       [10,  9, 18]])

In [91]:
a4[2][1]

4

In [93]:
a4[3][2]

9

In [107]:
a4[:,1:]#slicing

array([[ 4,  5],
       [ 2,  8],
       [ 1,  6],
       [ 9, 18]])

In [105]:
a4[1:3,0:2]

array([[7, 2],
       [9, 1]])