In [1]:
#imp features of panda
#data structure,data cleaning,indexing,slicing,data aggregation,transformation,data visualization,time-series handling,integration

In [9]:
import pandas as pd #import panda

In [13]:
#create panda series using list
data=[10,20,30,40,50]
series=pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [11]:
data=[10,20,30,40,'A']
series=pd.Series(data)
print(series)

0     A
1    20
2    30
3    40
4    50
dtype: object


In [15]:
data=[10,20,30,40,50] #custom index
i=['A','B','C','D','E']
series=pd.Series(data,index =i)
print(series)



A    10
B    20
C    30
D    40
E    50
dtype: int64


In [21]:
data={'a':10,'b':20,'c':30,'d':40}
series=pd.Series(data)
print(series)

a    10
b    20
c    30
d    40
dtype: int64


In [23]:
series.replace(20,50) #replacing element

a    10
b    50
c    30
d    40
dtype: int64

In [29]:
#create series using numpy
import numpy as np
data=np.array([200,200,300,400])
series=pd.Series(data,index=['(i)','(ii)','(iii)','(iv)'])
print(series)


(i)      200
(ii)     200
(iii)    300
(iv)     400
dtype: int32


In [35]:
#create data frame from a dict
data={'Name':['Alice','Bob','Mary'],'Age':[25,30,35],'Country':["USA",'UK','AUS']}
df=pd.DataFrame(data,index=[1,2,3])
print(df)

    Name  Age Country
1  Alice   25     USA
2    Bob   30      UK
3   Mary   35     AUS


In [51]:
import numpy as np
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df=pd.DataFrame(array,columns=['i','ii','iii'],index=[1,2,3])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   i  ii  iii
1  1   2    3
2  4   5    6
3  7   8    9


In [43]:
import numpy as np
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df=pd.DataFrame(array)
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [ ]:
punc_marks=['"',',','.']
text="""Sanjay’s hasn’t been an easy journey, but the joint effort of his family and, above all, the dogged determination of Sanjay himself, helped in his evolution from a reluctant learner to an accomplished artiste.\
It’s also about his well-wishers, mentors, audiences and fans.It’s fascinating to read how a playful boy from Mylapore gets initiated into music because of the deep-rooted socio-cultural milieu of his family. This five-decade long story is also about Carnatic music during the same period — besides Sanjay’s journey, you also get a ringside view of the lives of all the major characters in his life."""
for symbol in text:
    if symbol in punc_marks:
        text=text.replace(symbol,"")
text